### ISSUE TITLE
Consult about ROSCO related issues

### ISSUE THREAD

**Issue by Francis599** [NREL/ROSCO#119]
Dear all,
When I run 5MW_Land_Simulink.fst in the file " ROSCO-main\Test_Cases\5MW_Land_Simulink", it often occures fatal errors like "Invalid numerical input" or "Invalid logical input". I dout if the ROSCO_2.4 only refers to OPENFAST_2.4？ Because I use OPENFAST_3.1 but I only find the latest version  ROSCO_2.4 on this web.

**Comment by nikhar-abbas** [comment]
@Francis599, the specific OpenFAST version should not matter in this case.

Are you running the model through MATLAB/Simulink, or calling OpenFAST from the command line. If you are calling OpenFAST from the command line, please use runFAST.m from ROSCO's MATLAB toolbox to simulate the turbine instead: 
https://github.com/NREL/ROSCO/tree/main/Matlab_Toolbox

Otherwise, could you please provide more information about the error? It is hard to diagnose with such little information.

**Comment by dzalkind** [comment]
Hi @Francis599,

The `main` branch of ROSCO has OpenFAST 3.0.0 Test_Cases/ and the `develop` branch has v3.1.0.  We will be merging `develop` into `main` and releasing sometime this week.  ROSCO does not require any specific version of OpenFAST at this time, but, as Jason said, you need properly formatted input files for the different versions of OpenFAST.

This might be what you are looking for: https://github.com/NREL/ROSCO/tree/develop/Test_Cases/IEA-15-240-RWT-UMaineSemi

Dan

**Comment by Chueh-Cherng-Jer** [comment]
Dear all.
When I run the IEA-15-240-RWT-UMaineSemi, it link to the simulink.
But it comes up with the error.
Do you have a solution ?
![image](https://user-images.githubusercontent.com/105710391/168993336-cdcc61c1-a454-4337-a5f6-1cf4750400a7.png)

**Comment by dzalkind** [comment]
Hi,

OpenFAST needs to output the channels that Simulink reads from OutList.  I pushed a small fix here: https://github.com/NREL/ROSCO/pull/135

**Comment by Chueh-Cherng-Jer** [comment]
Thank for you answering me!
This question is solved, but there is another problem!
It means that the input port number and output port number is different!
![image](https://user-images.githubusercontent.com/105710391/169497154-874484ee-c37d-4e72-8cab-bb83cc273a8c.png)

**Comment by dzalkind** [comment]
Hmm, the OpenFAST Sfunction is looking for more inputs than your ROSCO Simulink model is providing it.  I'm not sure I can help you because it depends on your particular OpenFAST version.  Are you using cable or other structural controllers?   I believe I fixed this model so it works with OpenFAST 3.1.0 without any additional inputs, but you can look at the examples [here](https://github.com/OpenFAST/openfast/tree/main/glue-codes/simulink/examples) and tinker with your ROSCO Simulink model near the SFunction so it matches what the OpenFAST example has.

**Comment by Chueh-Cherng-Jer** [comment]
Thank you. I will try the solution.
There is another question.
I use the simulation file of IEA 15MW, and run the ROSCO, but it only runs for 7 seconds. 
Do you know what's wrong for my simulation?
![image](https://user-images.githubusercontent.com/105710391/169640536-b8f07705-a5b2-436f-a77d-c15711bba84f.png)

**Comment by Chueh-Cherng-Jer** [comment]
Thank for the advise.
I check the simulink file. It shows that the input port number does not match the output port number.
If I modify the number or do other to let it work.
<img width="458" alt="image" src="https://user-images.githubusercontent.com/105710391/169684011-944c9c9b-f9ce-41e6-aba3-9c4983a5d08a.png">

**Comment by dzalkind** [comment]
It seems like this is not an issue in ROSCO, but is more of a discussion of setting up OpenFAST with Simulink.  I would be happy to continue the thread on a discussion page.
