### ISSUE TITLE
v2.8.0 libdiscon_32bit.dll seems to be an out-of-date build

### ISSUE THREAD

**Issue by WilliamKeoghDnv** [NREL/ROSCO#384]
Hello,
When I run the built libdiscon_32bit.dll downloaded for v2.8.0 it prints startup message “Running ROSCO-v2.6.0”, so it seems this is an out of date build. 

The v2.8.0 source code has only version string “v2.8.0” - no “v2.6.0” anywhere - and the build timestamp for libdiscon_32bit.dll is months older than for the other built executables (April vs July), so looks like its not a correct build.

Would you mind re-running the build for v2.8.0 libdiscon_32bit.dll? Or at least delete the dll so it does not confuse anyone else?

Thanks.

**Comment by dzalkind** [comment]
Hi,

If you delete a line from the DISCON that's not relevant to the controller you're using, does the library still work and throw a warning about default values?  I do recall there being a misprint in that version's label, despite the tagged version being correct.  Can you verify that for me?

I've been relying on folks from DNV to build 32-bit ROSCO versions recently because I no longer have a reliable set up.

Best, Dan

**Comment by WilliamKeoghDnv** [comment]
Thanks for quick response. I deleted line "0                   ! IPC_ControlMode.... " from discon.in text and it prints
" ROSCO Warning: Did not find IPC_ControlMode in input file.  Using default value of            0"
What does that tell you?

Who at DNV is doing the win32 builds for you? I could ask them.

Thanks,
Will

**Comment by dzalkind** [comment]
That tells me it is ROSCO v2.8.0, or greater.  I can make a note of this.  Sorry for the confusion.  

I got help from Will Collier and Sigurd Jensen on the compilation.

**Comment by WilliamKeoghDnv** [comment]
Thanks Dan. I will take this up with Will and Sigurd and see if we can get a correct build.
