### ISSUE TITLE
run test IEA-15-240-RWT-UMaineSemi

### ISSUE THREAD

**Issue by robytian** [NREL/ROSCO#69]
If I want to run this test on Windows, which DLL do I need?
I am currently using the release version of Discon. DLL provided by OpenFast, which can be run. However, the BTS turbulent wind file generated by myself has the following error when running. Is it because of the controller?
![QQ图片20210925163501](https://user-images.githubusercontent.com/86820784/134768384-becfd2b4-ab17-4a02-bba6-41c212ae753c.png)
This is my .inp file:
<img width="372" alt="微信图片_20210925183232" src="https://user-images.githubusercontent.com/86820784/134768386-109050e9-cf91-49f6-a187-5d5089d7aab6.png">

**Comment by ghylander** [comment]
what is your time step?
try reducing it

**Comment by dzalkind** [comment]
This controller is not technically the ROSCO controller, so it might be outside of the scope of this repo and might be a better question [here](https://github.com/OpenFAST/r-test) or [here](https://wind.nrel.gov/forum/wind/viewforum.php?f=21&sid=43e59886fb1b6f7f01fe075390e5753c) because I think it has to do with the OpenFAST model.  Like @ghylander said, you might be running with too long of a timestep.  The way I like to debug these issues is to plot the OpenFAST output of the first 80 seconds before the tower strike.  Note that you'll need to set `OutFileFmt` to `1` or `3` in the primary OpenFAST input file to have a text-based output.
