### ISSUE TITLE
toolbox_schema.yaml not copied to venv site-packages, .yaml reading bug, reading old openfast .fst files

### ISSUE THREAD

**Issue by ghylander** [NREL/ROSCO#81]
I'm trying to run example 04 to tune a controller to a platform:
(I had a pre-existing conda env "rosco-env" from the now old ROSCO_toolbox repo)

1. I activate rosco-env

2. I navigate to the new ROSCO dir and run `python run_setup.py install`, exits with no errors

3. I go to /Examples and run example_04.py

4. I get the following error:
```
File ".\example_04.py", line 20, in <module>
from ROSCO_toolbox.inputs.validation import load_rosco_yaml
ModuleNotFoundError: No module named 'ROSCO_toolbox.inputs'
```

**Comment by ghylander** [comment]
> You can either edit the files in `ofTools/` 
This was the point of my question. I'm no t asking you to support any OF other than the latest release, but can I simply comment out those lines? Are they required by ROSCO to function properly?

> For problem 1 and #82, I think you should start with a fresh conda environment. A few other users have had similar issues and that resolved them.
I've tried this multiple times, I can make a screen recording if you want to check. The process I'm following is `conda create -y --name rosco-env python=3.8` > `conda activate rosco-env` > `conda install --y wisdem` > `python setup.py install` > try to run example_04.py > it fails

This raises the error that requires me to manually copy the toolbox_schema.yaml to the env directory

If you doubt my words, I can make a screen recording of this process


Besides this, what about the `KeyError: 'twr_freq'` when `Fl_Mode=1`? is it confirmed to be a bug?

**Comment by ghylander** [comment]
I'm not an expert on .egg, but the file in rosco.egg-info/SOURCES.txt is missing the line `ROSCO_toolbox/inputs/toolbox_schema.yaml`, which means the file is not being copied to the venv .egg

**Comment by dzalkind** [comment]
Hi @ghylander,

Thanks for clarifying.  Typically, we set up the ROSCO_toolbox using `python setup.py develop`.  We are not egg experts either, so if you find a solution that works for you, please submit a PR to help other users like yourself.

Commenting out lines in `ofTools` should be fine, but you won't know until you try it :-)

**Comment by nikhar-abbas** [comment]
Okay, just to follow up on this.

I made a few updates to #83 to address the install issue, hopefully bugs are fixed. I added your suggested `package_data={'': ['*.yaml']}` line to the setup.py and modified the CI testing so that it does a `python setup.py install` when installing ROSCO to run the examples. This seems to run all of the examples as expected. You can see that example 04 is running here:
https://github.com/NREL/ROSCO/runs/4082629091?check_suite_focus=true#step:8:343

Note that the tests are failing because the examples that use OpenFAST are not running right now. This is because of a known issue with the conda-forge distribution of OpenFAST which is currently being fixed.

As far as the `twr_freq` issue you are seeing - I would not say this is a known bug. I realized now that there is some inconsistency in the example tuning yamls as to which section the `twr_freq` and `ptfm_freq` parameters are in - please note that they are now in the `controller_params` section. Sorry about any confusion here. I have updated the yamls in #83  as well.
https://github.com/NREL/ROSCO/blob/ecef7ae52881843707f06675a611e99d09ca00e6/ROSCO_toolbox/inputs/toolbox_schema.yaml#L269

As long as the input lines that you comment out in FAST_reader.py are not for parameters specifically used in the tuning process, it should be fine.

**Comment by ghylander** [comment]
Great news about the `install` workflow, I didn't know what else could be the reason it wasn't working for me.

Regarding the examples yaml, it was confusing indeed, thanks for the clarification

I will try to comment out the lines and see the results

Lastly, thanks to you, Daniel and Rafael (and any other researcher I have not been in contact with so far) for developing and supporting ROSCO, I think it's a great tool and I'm more than happy to help streamline it.
